DROP TRIGGER IF EXISTS t_new_user on users;
DROP TRIGGER IF EXISTS t_delete_user on users;
DROP TRIGGER IF EXISTS t_update_users ON users;
DROP TRIGGER IF EXISTS t_update_channels ON channels;
DROP TRIGGER IF EXISTS t_delete_channel ON channels;
DROP TRIGGER IF EXISTS t_update_bans ON bans;
DROP TRIGGER IF EXISTS t_delete_ban ON bans;
DROP TRIGGER IF EXISTS t_update_levels on levels;
DROP TRIGGER IF EXISTS t_delete_level on levels;
DROP FUNCTION IF EXISTS update_users();
DROP FUNCTION IF EXISTS update_channels();
DROP FUNCTION IF EXISTS update_levels();
DROP FUNCTION IF EXISTS update_bans();
DROP FUNCTION IF EXISTS new_user();
DROP FUNCTION IF EXISTS delete_user();
DROP FUNCTION IF EXISTS delete_channel();
DROP FUNCTION IF EXISTS delete_level();
DROP FUNCTION IF EXISTS delete_ban();
DROP INDEX IF EXISTS help_topic_idx;
DROP INDEX IF EXISTS help_language_id_idx;
DROP INDEX IF EXISTS bans_expires_idx;
DROP INDEX IF EXISTS bans_channelkey_idx;
DROP INDEX IF EXISTS users_username_idx;
DROP INDEX IF EXISTS users_email_idx;
DROP INDEX IF EXISTS users_signup_ts_idx;
DROP INDEX IF EXISTS users_signup_ip_idx;
DROP INDEX IF EXISTS levels_access_idx;
DROP INDEX IF EXISTS levels_userid_idx;
DROP INDEX IF EXISTS levels_suspendexpires_idx;
DROP INDEX IF EXISTS channellog_channelID_idx;
DROP INDEX IF EXISTS channellog_event_idx;
DROP INDEX IF EXISTS userlog_channelID_idx;
DROP INDEX IF EXISTS userlog_event_idx;
DROP INDEX IF EXISTS supporters_support_idx;
DROP INDEX IF EXISTS supporters_user_id_idx;
DROP INDEX IF EXISTS pending_status_idx;
DROP INDEX IF EXISTS pending_manager_id_idx;
DROP INDEX IF EXISTS pending_traffic_channel_id_idx;
DROP INDEX IF EXISTS pending_chanfix_scores_channel_id_idx;
DROP INDEX IF EXISTS domain_domain_idx;
DROP INDEX IF EXISTS noreg_user_name_idx;
DROP INDEX IF EXISTS noreg_email_idx;
DROP INDEX IF EXISTS noreg_channel_name_idx;
DROP INDEX IF EXISTS noreg_expire_time_idx;
DROP INDEX IF EXISTS adminlog_c_idx;
DROP INDEX IF EXISTS adminlog_u_idx;
DROP INDEX IF EXISTS adminlog_a_idx;
DROP INDEX IF EXISTS adminlog_i_idx;
DROP INDEX IF EXISTS ip_restrict_idx;
DROP TABLE IF EXISTS translations;
DROP TABLE IF EXISTS help;
DROP TABLE IF EXISTS bans;
DROP TABLE IF EXISTS users_lastseen;
DROP TABLE IF EXISTS user_sec_history;
DROP TABLE IF EXISTS levels;
DROP TABLE IF EXISTS channellog;
DROP TABLE IF EXISTS userlog;
DROP TABLE IF EXISTS supporters;
DROP TABLE IF EXISTS pending;
DROP TABLE IF EXISTS pending_traffic;
DROP TABLE IF EXISTS pending_chanfix_scores;
DROP TABLE IF EXISTS domain;
DROP TABLE IF EXISTS deletion_transactions;
DROP TABLE IF EXISTS noreg;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS notices;
DROP TABLE IF EXISTS variables;
DROP TABLE IF EXISTS adminlog;
DROP TABLE IF EXISTS ip_restrict;
DROP TABLE IF EXISTS webnotices;
DROP TABLE IF EXISTS glines;
DROP TABLE IF EXISTS whitelist;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS languages;
