version: "2"
run:
  go: "1.24"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude SHA1 warnings for OATH OTP implementation (required by RFC)
    - path: internal/auth/oath/oath_otp.go
      linters: [gosec]
      text: "G505: Blocklisted import crypto/sha1"

    - path: internal/auth/oath/oath_otp.go
      linters: [gosec]
      text: "G401: Use of weak cryptographic primitive"

    # Add a comment explaining why this is safe
    # nolint:gosec // SHA1 is required by RFC 4226 (HOTP) and RFC 6238 (TOTP)
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
