FROM golang:1.25-alpine

RUN apk add --no-cache make git bash

WORKDIR /app

COPY docker-entrypoint.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

ENTRYPOINT ["docker-entrypoint.dev.sh"]
