// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: noreg.sql

package models

import (
	"context"
)

const checkUserNoregStatus = `-- name: CheckUserNoregStatus :one

SELECT COUNT(*) > 0 as is_noreg
FROM noreg 
WHERE (lower(user_name) = lower($1) OR $1 = '')
  AND (expire_time IS NULL OR expire_time > EXTRACT(EPOCH FROM NOW())::int)
`

// NOREG table queries for checking user restrictions
// Checks if a user has NOREG status
func (q *Queries) CheckUserNoregStatus(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserNoregStatus, lower)
	var is_noreg bool
	err := row.Scan(&is_noreg)
	return is_noreg, err
}
