// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user_role.sql

package models

import (
	"context"
)

const addMultipleUserRoles = `-- name: AddMultipleUserRoles :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, id
FROM roles
WHERE name = ANY($2)
`

type AddMultipleUserRolesParams struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) AddMultipleUserRoles(ctx context.Context, arg AddMultipleUserRolesParams) error {
	_, err := q.db.Exec(ctx, addMultipleUserRoles, arg.UserID, arg.Name)
	return err
}

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
`

type AddUserRoleParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.name, r.description, r.created_at, r.updated_at, r.created_by, r.updated_by
FROM user_roles ur
INNER JOIN roles r
ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.id ASC
`

func (q *Queries) ListUserRoles(ctx context.Context, userID int32) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMultipleUserRoles = `-- name: RemoveMultipleUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id IN (
    SELECT id
    FROM roles
    WHERE name = ANY($2)
)
`

type RemoveMultipleUserRolesParams struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) RemoveMultipleUserRoles(ctx context.Context, arg RemoveMultipleUserRolesParams) error {
	_, err := q.db.Exec(ctx, removeMultipleUserRoles, arg.UserID, arg.Name)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type RemoveUserRoleParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserRole, arg.UserID, arg.RoleID)
	return err
}
