// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: whitelist.sql

package models

import (
	"context"

	"github.com/jackc/pgtype"
)

const getWhiteListByIP = `-- name: GetWhiteListByIP :one
SELECT id, ip, addedby, addedon, expiresat, reason
FROM whitelist
WHERE ip = $1 LIMIT 1
`

func (q *Queries) GetWhiteListByIP(ctx context.Context, ip pgtype.Inet) (Whitelist, error) {
	row := q.db.QueryRow(ctx, getWhiteListByIP, ip)
	var i Whitelist
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.Addedby,
		&i.Addedon,
		&i.Expiresat,
		&i.Reason,
	)
	return i, err
}
